### ISSUE TITLE
build and use

### ISSUE THREAD

**Issue by rootSectornet** [shinyoshiaki/node-sfu#2]
how to build and use this project, Please 

i create video conference , and i use [Node-Webrtc](https://github.com/node-webrtc/node-webrtc)  for help routing all stream from each client. but every server have 18 more connection my service always hang dan every connection will diconnected.

i don't know what is wrong in my code

[this my code repository
](https://github.com/rootSectornet/video_conference)
I would love if you could tell me what was wrong

**Comment by shinyoshiaki** [comment]
added Readme.md, please check it

**Comment by shinyoshiaki** [comment]
I don't use node-webrtc so I don't know how to use node-webrtc.
This project is full scratch SFU implementation for node.js

**Comment by rootSectornet** [comment]
how to use turn server?

**Comment by shinyoshiaki** [comment]
Because SFU are usually located in a global IP environment, SFU do not usually use TURN.
Therefore, it is the client side (e.g. browser) that needs to TURN setting.
https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/urls#Examples

**Comment by rootSectornet** [comment]
can you teach me, how you routing each stream?
